# PRE plays
# From project-config/playbooks/base/pre.yaml
- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.openstack.org"

- hosts: all
  roles:
    - add-build-sshkey
#     - start-zuul-console
#     - configure-unbound
    - validate-host
    - use-cached-repos
#     - mirror-workspace-git-repos
#     - mirror-info
#     - configure-mirrors
    - role: fetch-zuul-cloner
      destination: "/usr/zuul-env/bin/zuul-cloner"
      repo_src_dir: "/home/ubuntu/src/git.openstack.org"

- include: work/src/git.openstack.org/openstack-infra/zuul-jobs/playbooks/multinode/pre.yaml
- include: work/src/git.openstack.org/openstack-dev/devstack/playbooks/pre.yaml

# RUN play
# Devstack run
- include: work/src/git.openstack.org/openstack-dev/devstack/playbooks/devstack.yaml

# Tempest run
# - include: work/src/git.openstack.org/openstack/tempest/playbooks/devstack-tempest.yaml

# POST plays - enable on demand for testing
#- include: work/src/git.openstack.org/openstack/tempest/playbooks/post-tempest.yaml
#- include: work/src/git.openstack.org/openstack-dev/devstack/playbooks/post.yaml
#- include: work/src/git.openstack.org/openstack-infra/project-config/playbooks/base/post-ssh.yaml
#- include: work/src/git.openstack.org/openstack-infra/project-config/playbooks/base/post-logs.yaml
