# From project-config/playbooks/base/pre.yaml

- hosts: localhost
  roles:
    - role: emit-job-header
      zuul_log_url: "http://logs.openstack.org"

- hosts: all
  roles:
    - add-build-sshkey
#     - start-zuul-console
#     - configure-unbound
    - validate-host
    - use-cached-repos
#     - mirror-workspace-git-repos
#     - mirror-info
#     - configure-mirrors
    - role: fetch-zuul-cloner
      destination: "/usr/zuul-env/bin/zuul-cloner"
      repo_src_dir: "/home/ubuntu/src/git.openstack.org"

- include: work/src/git.openstack.org/openstack-infra/zuul-jobs/playbooks/multinode/pre.yaml
